// Generated by gourd (version 0.1dev)
// Generated at 2015/06/06 18:43:19 (+0200)
// Note: If you want to re-generate this file in the future,
//       do not change it.

package oauth2

import (
	"github.com/gourd/service"
	"github.com/gourd/service/upperio"
	"log"
	"net/http"
	"upper.io/db"
)

func init() {
	service.Providers.Define("AccessData", GetAccessDataService)
}

// GetAccessDataService implements service.ProviderFunc
func GetAccessDataService(r *http.Request) (s service.Service, err error) {

	// obtain database
	db, err := upperio.Open(r, "default")
	if err != nil {
		return
	}

	// define service and return
	s = &AccessDataService{db}
	return
}

// AccessDataService serves generic CURD for type AccessData
// Generated by gourd CLI tool
type AccessDataService struct {
	Db db.Database
}

// Create a AccessData in the database, of the parent
func (s *AccessDataService) Create(
	cond service.Conds, ep service.EntityPtr) (err error) {

	// get collection
	coll, err := s.Coll()
	if err != nil {
		return
	}

	//TODO: convert cond into parentkey and
	//      enforce to the entity

	// add the entity to collection
	id, err := coll.Append(ep)
	if err != nil {
		log.Printf("Error creating AccessData: %s", err.Error())
		err = service.ErrorInternal
		return
	}

	//TODO: apply the key to the entity
	e := ep.(*AccessData)
	e.Id = int32(id.(int64))

	return
}

// Search a AccessData by its condition(s)
func (s *AccessDataService) Search(
	c service.Conds, lp service.EntityListPtr) (err error) {

	// get collection
	coll, err := s.Coll()
	if err != nil {
		return
	}

	// get list condition and ignore the error
	cond, _ := c.GetMap()

	// retrieve all users
	res := coll.Find(db.Cond(cond))

	// TODO: also work with c.Cond for ListCond (limit and offset)
	err = res.All(lp)
	if err != nil {
		err = service.ErrorInternal
	}

	return nil
}

// One returns the first AccessData matches condition(s)
func (s *AccessDataService) One(
	c service.Conds, ep service.EntityPtr) (err error) {

	// retrieve from database
	l := &[]AccessData{}
	err = s.Search(c, l)
	if err != nil {
		return
	}

	// if not found, report
	if len(*l) == 0 {
		err = service.ErrorNotFound
		return
	}

	// assign the value of given point
	// to the first retrieved value
	(*ep.(*AccessData)) = (*l)[0]
	return nil
}

// Update AccessData on condition(s)
func (s *AccessDataService) Update(
	c service.Conds, ep service.EntityPtr) (err error) {

	// get collection
	coll, err := s.Coll()
	if err != nil {
		return
	}

	// get by condition and ignore the error
	cond, _ := c.GetMap()
	res := coll.Find(db.Cond(cond))

	// update the matched entities
	err = res.Update(ep)
	if err != nil {
		log.Printf("Error updating AccessData: %s", err.Error())
		err = service.ErrorInternal
	}
	return
}

// Delete AccessData on condition(s)
func (s *AccessDataService) Delete(
	c service.Conds) (err error) {

	// get collection
	coll, err := s.Coll()
	if err != nil {
		return
	}

	// get by condition and ignore the error
	cond, _ := c.GetMap()
	res := coll.Find(db.Cond(cond))

	// remove the matched entities
	err = res.Remove()
	if err != nil {
		log.Printf("Error deleting AccessData: %s", err.Error())
		err = service.ErrorInternal
	}
	return nil
}

// AllocEntity allocate memory for an entity
func (s *AccessDataService) AllocEntity() service.EntityPtr {
	return &AccessData{}
}

// AllocEntity allocate memory for an entity list
func (s *AccessDataService) AllocEntityList() service.EntityListPtr {
	return &[]AccessData{}
}

// Len inspect the length of an entity list
func (s *AccessDataService) Len(pl service.EntityListPtr) int64 {
	el := pl.(*[]AccessData)
	return int64(len(*el))
}

// Coll return the raw upper.io collection
func (s *AccessDataService) Coll() (coll db.Collection, err error) {
	// get raw collection
	coll, err = s.Db.Collection("oauth2_access")
	if err != nil {
		log.Printf("Error connecting collection oauth2_access: %s",
			err.Error())
		err = service.ErrorInternal
	}
	return
}
