// Generated by gourd (version 0.1dev)
// Generated at 2015/08/14 22:52:43 (+0800)
// Note: If you want to re-generate this file in the future,
//       do not change it.

package oauth2

import (
	"github.com/gourd/service"
	"github.com/gourd/service/upperio"
	"net/http"

	"log"
	"upper.io/db"
)

func init() {
	// define service provider with proxy
	service.Providers.DefineFunc("User", func(r *http.Request) (s service.Service, err error) {
		return GetUserService(r)
	})
}

// GetUserService provides raw UserService
func GetUserService(r *http.Request) (s *UserService, err error) {

	// obtain database
	db, err := upperio.Open(r, "default")
	if err != nil {
		return
	}

	// define service and return
	s = &UserService{db}
	return
}

// UserService serves generic CURD for type User
// Generated by gourd CLI tool
type UserService struct {
	Db db.Database
}

// Close the database session
func (s *UserService) Close() error {
	return s.Db.Close()
}

// Create a User in the database, of the parent
func (s *UserService) Create(
	cond service.Conds, ep service.EntityPtr) (err error) {

	// get collection
	coll, err := s.Coll()
	if err != nil {
		return
	}

	// apply random uuid string to string id

	//TODO: convert cond into parentkey and
	//      enforce to the entity

	// add the entity to collection

	id, err := coll.Append(ep)

	if err != nil {
		log.Printf("Error creating User: %s", err.Error())
		err = service.ErrorInternal
		return
	}

	// apply the key to the entity
	e := ep.(*User)
	e.Id = int64(id.(int64))

	return
}

// Search a User by its condition(s)
func (s *UserService) Search(
	c service.Conds, lp service.EntityListPtr) (err error) {

	// get collection
	coll, err := s.Coll()
	if err != nil {
		return
	}

	// get list condition and ignore the error
	cond, _ := c.GetMap()

	// retrieve all users
	var res db.Result
	if len(cond) == 0 {
		res = coll.Find()
	} else {
		res = coll.Find(db.Cond(cond))
	}

	// handle paging
	if c.GetOffset() != 0 {
		res = res.Skip(uint(c.GetOffset()))
	}
	if c.GetLimit() != 0 {
		res = res.Limit(uint(c.GetLimit()))
	}

	// TODO: also work with c.Cond for ListCond (limit and offset)
	err = res.All(lp)
	if err != nil {
		err = service.ErrorInternal
	}

	return nil
}

// One returns the first User matches condition(s)
func (s *UserService) One(
	c service.Conds, ep service.EntityPtr) (err error) {

	// retrieve from database
	l := &[]User{}
	err = s.Search(c, l)
	if err != nil {
		return
	}

	// if not found, report
	if len(*l) == 0 {
		err = service.ErrorNotFound
		return
	}

	// assign the value of given point
	// to the first retrieved value
	(*ep.(*User)) = (*l)[0]
	return nil
}

// Update User on condition(s)
func (s *UserService) Update(
	c service.Conds, ep service.EntityPtr) (err error) {

	// get collection
	coll, err := s.Coll()
	if err != nil {
		return
	}

	// get by condition and ignore the error
	cond, _ := c.GetMap()
	res := coll.Find(db.Cond(cond))

	// update the matched entities
	err = res.Update(ep)
	if err != nil {
		log.Printf("Error updating User: %s", err.Error())
		err = service.ErrorInternal
	}
	return
}

// Delete User on condition(s)
func (s *UserService) Delete(
	c service.Conds) (err error) {

	// get collection
	coll, err := s.Coll()
	if err != nil {
		return
	}

	// get by condition and ignore the error
	cond, _ := c.GetMap()
	res := coll.Find(db.Cond(cond))

	// remove the matched entities
	err = res.Remove()
	if err != nil {
		log.Printf("Error deleting User: %s", err.Error())
		err = service.ErrorInternal
	}
	return nil
}

// AllocEntity allocate memory for an entity
func (s *UserService) AllocEntity() service.EntityPtr {
	return &User{}
}

// AllocEntityList allocate memory for an entity list
func (s *UserService) AllocEntityList() service.EntityListPtr {
	return &[]User{}
}

// Len inspect the length of an entity list
func (s *UserService) Len(pl service.EntityListPtr) int64 {
	el := pl.(*[]User)
	return int64(len(*el))
}

// Coll return the raw upper.io collection
func (s *UserService) Coll() (coll db.Collection, err error) {
	// get raw collection
	coll, err = s.Db.Collection("user")
	if err != nil {
		log.Printf("Error connecting collection user: %s",
			err.Error())
		err = service.ErrorInternal
	}
	return
}
